# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
-   main: dxda.go
-
    main: ./cmd/dx-download-agent/dx-download-agent.go
    binary: dx-download-agent


