sudo: required

services:
  - docker

before_install:
- docker build -t dnanexus/dxda .

script:
- docker run -v $PWD:/workdir -w /workdir -e DX_API_TOKEN=$DX_API_TOKEN dnanexus/dxda download -max_threads=`nproc` test_files/single_file.manifest.json.bz2
