sudo: required

services:
  - docker

before_install:
  - docker build -t dnanexus/dxda:$TRAVIS_COMMIT .

script:
  # Placeholder for running an entire test suite
  - docker run -v $PWD:/workdir -w /workdir -e DX_API_TOKEN=$DX_API_TOKEN dnanexus/dxda:$TRAVIS_COMMIT download -max_threads=`nproc` test_files/single_file.manifest.json.bz2
  # If all the tests pass, push the docker image and create a release
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dnanexus/dxda:$TRAVIS_COMMIT
